# In fordham_law_search, we do NOT keep this file in the repository AT ALL,
# and put production secrets directly in it. It should be shared
# through other means. Production deploy TBD.
#
# You can load on heroku with production secrets heroku by:
#
#      bundle exec rake heroku:secrets RAILS_ENV=production
#
# This is using https://github.com/alexpeattie/heroku_secrets

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  eds_api_user_id:
  eds_api_password:

# Since we only have one set of eds api auth and other auth, we merge
# production in for conveninence.
development:
  <<: *production
  secret_key_base: 22cd9b981d666e5e94d38567eacb5a50a23b83578757eccd5d30b21aa99203d3f268a72d9f87144d50e436b862b38f011c2fa7eed353a8c7bf2b736e98737c67

test:
  secret_key_base: 163abd4644e125bdb06391da56435cb841909085984c45b07bdf713f9386e397f267ae9ef925eef3550e2a4d56058d411a9db56575dd1e690cd24641e72b6d8f

